# Required Metadata
sonar.organization=protap-club
sonar.projectKey=Protap-Club_School-Management-System
sonar.projectName=School Management System
sonar.projectVersion=1.0

# Path to the source code
# Based on your project structure, including the root helps Sonar see the Dockerfiles too
sonar.sources=backend/src ,frontend/src
# If you want to be specific to source folders only:
# sonar.sources=backend/src,frontend/src

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# JavaScript specific configurations
sonar.javascript.environments=node,browser
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Host URL for SonarCloud
sonar.host.url=https://sonarcloud.io
